
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.VBox vbox3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.CheckButton ToUpperCheckButton;

	private global::Gtk.CheckButton TurnStringCheckButton;

	private global::Gtk.CheckButton AddSpacesCheckButton;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Entry TextField;

	private global::Gtk.Label TextLabel;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Button StartButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.ToUpperCheckButton = new global::Gtk.CheckButton();
		this.ToUpperCheckButton.CanFocus = true;
		this.ToUpperCheckButton.Name = "ToUpperCheckButton";
		this.ToUpperCheckButton.Label = global::Mono.Unix.Catalog.GetString("ToUpper");
		this.ToUpperCheckButton.DrawIndicator = true;
		this.ToUpperCheckButton.UseUnderline = true;
		this.vbox4.Add(this.ToUpperCheckButton);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.ToUpperCheckButton]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.TurnStringCheckButton = new global::Gtk.CheckButton();
		this.TurnStringCheckButton.CanFocus = true;
		this.TurnStringCheckButton.Name = "TurnStringCheckButton";
		this.TurnStringCheckButton.Label = global::Mono.Unix.Catalog.GetString("TurnString");
		this.TurnStringCheckButton.DrawIndicator = true;
		this.TurnStringCheckButton.UseUnderline = true;
		this.vbox4.Add(this.TurnStringCheckButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.TurnStringCheckButton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.AddSpacesCheckButton = new global::Gtk.CheckButton();
		this.AddSpacesCheckButton.CanFocus = true;
		this.AddSpacesCheckButton.Name = "AddSpacesCheckButton";
		this.AddSpacesCheckButton.Label = global::Mono.Unix.Catalog.GetString("AddSpaces");
		this.AddSpacesCheckButton.DrawIndicator = true;
		this.AddSpacesCheckButton.UseUnderline = true;
		this.vbox4.Add(this.AddSpacesCheckButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.AddSpacesCheckButton]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox3.Add(this.vbox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.TextField = new global::Gtk.Entry();
		this.TextField.CanFocus = true;
		this.TextField.Name = "TextField";
		this.TextField.IsEditable = true;
		this.TextField.MaxLength = 500;
		this.TextField.InvisibleChar = '•';
		this.vbox7.Add(this.TextField);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.TextField]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.TextLabel = new global::Gtk.Label();
		this.TextLabel.Name = "TextLabel";
		this.vbox7.Add(this.TextLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.TextLabel]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox3.Add(this.vbox7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox7]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox3.Add(this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox3]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.StartButton = new global::Gtk.Button();
		this.StartButton.CanFocus = true;
		this.StartButton.Name = "StartButton";
		this.StartButton.UseUnderline = true;
		this.StartButton.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.vbox5.Add(this.StartButton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.StartButton]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add(this.vbox5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox2.Add(this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.Add(this.hbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 442;
		this.DefaultHeight = 442;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.StartButton.Clicked += new global::System.EventHandler(this.OnStartButtonClicked);
	}
}
